# Generated by Django 3.2.4 on 2021-06-23 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signin', '0002_auto_20210623_0630'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='email',
            field=models.EmailField(default=0, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='destination',
            name='name',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='destination',
            name='password',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
