# Generated by Django 3.2.4 on 2021-06-24 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('signin', '0004_auto_20210624_0044'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='destination',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='destination',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='destination',
            name='password',
        ),
    ]
